### ISSUE TITLE
rosetta not work on NodeJS

### ISSUE THREAD

**Issue by sergio11** [SUI-Components/rosetta#16]
Hi there,
I am internationalizing my application and I have problems with rosetta and react-router in node

Here you have the express boot error:

> nodemon server.js
C:\Users\Sergio\lik\app\routes.js:36
i18n.setTranslationsSilent(_languages2.default['en']);
**TypeError: i18n.setTranslationsSilent is not a function**
    at Object.<anonymous> (routes.js:10:6)
    at Module._compile (module.js:425:26)
    at loader (C:\Users\Sergio\lik\node_modules\babel-register\lib\node.js:130:5
)

This is where Rosetta instantiate and adapter:
https://github.com/sergio11/lik/blob/master/app/routes.js

Here is the routing middleware
https://github.com/sergio11/lik/blob/master/server.js (line 22)

Thank you very much. Greetings

**Comment by carlosvillu** [comment]
Hola Sergio,

Siento no haberte respondido antes. El problema que tienes es porque estás usando la última versión de rosetta, en la que hemos cambiado completamente la API y borramos el método `setTranslationsSilent`

Con la nueva API creemos que hemos ganado en claridad.

Lo que tienes que hacer el "setear" tu diccionario de idiomas con el setter languages y luego cambiarlo a la cultura que desees. Por lo que tu fichero de rutas quedaría así:

```
const i18n = new Rosetta({adapter: new Polyglot()});
i18n.languages = languages;
i18n.culture = 'es';
i18n.addToContext(Route, languages); // Agregar languages aquí es opcional. Solo si lo vas a usar.

export default (
  <Route component={App}>
    <Route path='/' component={Home} />
  </Route>
);
```

La misma idea tienes que aplicar en tu middleware.

Como veo que estás trabajando con React-Router, en algún punto tendrás la necesidad de cambiar la cultura por URL. La estrategia que mejor nos ha funcionado a nosotros es un código como este:

```
const i18n = new Rosetta({adapter: new Polyglot()});
i18n.languages = languages;
i18n.culture = 'es';
i18n.addToContext(Route, languages); // Agregar languages aquí es opcional. Solo si lo vas a usar.

const AppRouter = (props, context) => {
  context.i18n.culture = props.params.lang;
  return (<App {...props} />);
}

export default (
  <Route path='/:lang' component={AppRouter}>
    <IndexRoute  component={Home} />
  </Route>
);
```

Cualquier cosa ya me comentas :)

**Comment by sergio11** [comment]
Hola Carlos.
Muchas Gracias por contestar, las verdad es que no me había dado cuenta de la versión.
Ahora tengo un problema con el context, este es pasado como un objeto vacío

const AppRouter = (props, context) => {
  context.i18n.culture = props.params.lang;
  return (<App {...props} />);
}
>

No sé si tiene que ver con lo que dices de aplicar la misma idea en el middleware. Ya  que no sé si aplicarlo sobre  el Router.RoutingContext o el Router.Router.

Un Saludo.

**Comment by carlosvillu** [comment]
Has definido el "contextType" de AppRouter ?!

Sobre lo otro. Deberías definir RouterContext en el server y Router en el cliente. 

Espero que te haya ayudado.

**Comment by sergio11** [comment]
Perfecto, era el RouterContext.

Gracias por todo.
