### ISSUE TITLE
Cargar solo textos de 1 idioma

### ISSUE THREAD

**Issue by julianmartinezmansell** [SUI-Components/rosetta#17]
Hola, es posible usar Polyglot y Rosetta para hacer una webapp isomorphica pero que solo se cargue la ficha de un idioma, y que no se tenga que cargar del webpack TODOS los idiomas y hagan la app pesada?

Gracias.

Que opinion tienes de otras librerias como estas?
https://github.com/i18next/react-i18next
https://github.com/l20n/l20n.js
https://github.com/alexdrel/i18n-react

**Comment by carlosvillu** [comment]
Hola Julian,

Realmente Rosetta no se encarga de como adquirir el diccionario de idiomas. Para no enviar todos los idiomas en el bundle que contiene tu aplicación, puedes hacer en el punto de entrada de tu App que antes de inicializar Rosetta hagas una llamada Ajax a un JSON que tengas en un CDN o en tu server, para traerte el diccionario. Una vez que lo tengas, ganas en que puedes cambiar de idioma tu app sin tener que hacer nuevas peticiones al server.

Otra cosa que puedes hacer es un función para "wrappear" el cambio de cultura que devuelva una promesa:

```js
const changeCulture = (culture, i18n) => {
  return axios.get('URL_PARA_MI_CULTURA').then(dicc => {
    i18n.languages = dicc
    i18n.culture = culture
  })
}
```

En este último caso dicc es un JSON que solo contiene la cultura que hayas pedido.

Sobre mi oponión de las otras librerías, realmente me parecen muy buenos proyectos, pero a nosotros en Schibsted no nos acababa de cerrar, por que tenemos varios proyectos legacy que ya están usando sus propias librerías de I18N  que nada tienen que ver con React. La idea fue crear algo que fácilmente nos permitiera integrar todas esas soluciones con React. Y por eso usamos Rosetta y sus adaptadores.

C.

**Comment by julianmartinezmansell** [comment]
Mil gracias por la respuesta... voy a intentar si lo puedo hacer por webpack. A ver si consigo que el pack me mande solo un idioma que necesito.
Gracias.

**Comment by julianmartinezmansell** [comment]
Carlos, 
Ahi puse online la nueva app en la que estoy trabajando. A ver si te gusta? Saludos
http://www.selio.com (desde el móvil)
